name: Say Hello

# Cada vez que se haga un push a la rama master se ejecutará el workflow
on:
  push:
    branches:
      - master


# Trabajos a realizar el workflow
jobs:
  hello:
    # usar una version estable de ubuntu porque en caso de que haya una nueva versión de ubuntu, el workflow se romperá
    runs-on: ubuntu-latest
    # Pasos a realizar en el trabajo
    steps:
      - name: Say Hello
        run: echo "Hello, world!"
      - name: Dime la fecha
        run: date
      - run: ls -l

